// This file contains a full list of countries with dialing codes and placeholder states/cities for demo purposes.
// For production, consider using a package like 'country-state-city' or an API for dynamic data.

const countryData = [
  { name: 'Afghanistan', code: '+93', states: [{ name: 'Kabul', cities: ['Kabul'] }] },
  { name: 'Albania', code: '+355', states: [{ name: 'Tirana', cities: ['Tirana'] }] },
  { name: 'Algeria', code: '+213', states: [{ name: 'Algiers', cities: ['Algiers'] }] },
  { name: 'Andorra', code: '+376', states: [{ name: 'Andorra la Vella', cities: ['Andorra la Vella'] }] },
  { name: 'Angola', code: '+244', states: [{ name: 'Luanda', cities: ['Luanda'] }] },
  { name: 'Argentina', code: '+54', states: [{ name: 'Buenos Aires', cities: ['Buenos Aires'] }] },
  { name: 'Armenia', code: '+374', states: [{ name: 'Yerevan', cities: ['Yerevan'] }] },
  { name: 'Australia', code: '+61', states: [{ name: 'New South Wales', cities: ['Sydney'] }] },
  { name: 'Austria', code: '+43', states: [{ name: 'Vienna', cities: ['Vienna'] }] },
  { name: 'Azerbaijan', code: '+994', states: [{ name: 'Baku', cities: ['Baku'] }] },
  { name: 'Bahamas', code: '+1-242', states: [{ name: 'New Providence', cities: ['Nassau'] }] },
  { name: 'Bahrain', code: '+973', states: [{ name: 'Capital', cities: ['Manama'] }] },
  { name: 'Bangladesh', code: '+880', states: [{ name: 'Dhaka', cities: ['Dhaka'] }] },
  { name: 'Barbados', code: '+1-246', states: [{ name: 'Saint Michael', cities: ['Bridgetown'] }] },
  { name: 'Belarus', code: '+375', states: [{ name: 'Minsk', cities: ['Minsk'] }] },
  { name: 'Belgium', code: '+32', states: [{ name: 'Brussels', cities: ['Brussels'] }] },
  { name: 'Belize', code: '+501', states: [{ name: 'Belize District', cities: ['Belize City'] }] },
  { name: 'Benin', code: '+229', states: [{ name: 'Littoral', cities: ['Cotonou'] }] },
  { name: 'Bhutan', code: '+975', states: [{ name: 'Thimphu', cities: ['Thimphu'] }] },
  { name: 'Bolivia', code: '+591', states: [{ name: 'La Paz', cities: ['La Paz'] }] },
  { name: 'Bosnia and Herzegovina', code: '+387', states: [{ name: 'Sarajevo', cities: ['Sarajevo'] }] },
  { name: 'Botswana', code: '+267', states: [{ name: 'South-East', cities: ['Gaborone'] }] },
  { name: 'Brazil', code: '+55', states: [{ name: 'São Paulo', cities: ['São Paulo'] }] },
  { name: 'Brunei', code: '+673', states: [{ name: 'Brunei-Muara', cities: ['Bandar Seri Begawan'] }] },
  { name: 'Bulgaria', code: '+359', states: [{ name: 'Sofia City', cities: ['Sofia'] }] },
  { name: 'Burkina Faso', code: '+226', states: [{ name: 'Kadiogo', cities: ['Ouagadougou'] }] },
  { name: 'Burundi', code: '+257', states: [{ name: 'Bujumbura Mairie', cities: ['Bujumbura'] }] },
  { name: 'Cabo Verde', code: '+238', states: [{ name: 'Praia', cities: ['Praia'] }] },
  { name: 'Cambodia', code: '+855', states: [{ name: 'Phnom Penh', cities: ['Phnom Penh'] }] },
  { name: 'Cameroon', code: '+237', states: [{ name: 'Centre', cities: ['Yaoundé'] }] },
  { name: 'Canada', code: '+1', states: [{ name: 'Ontario', cities: ['Toronto'] }] },
  { name: 'Central African Republic', code: '+236', states: [{ name: 'Bangui', cities: ['Bangui'] }] },
  { name: 'Chad', code: '+235', states: [{ name: 'N’Djamena', cities: ['N’Djamena'] }] },
  { name: 'Chile', code: '+56', states: [{ name: 'Santiago Metropolitan', cities: ['Santiago'] }] },
  { name: 'China', code: '+86', states: [{ name: 'Beijing', cities: ['Beijing'] }] },
  { name: 'Colombia', code: '+57', states: [{ name: 'Bogotá', cities: ['Bogotá'] }] },
  { name: 'Comoros', code: '+269', states: [{ name: 'Grande Comore', cities: ['Moroni'] }] },
  { name: 'Congo', code: '+242', states: [{ name: 'Brazzaville', cities: ['Brazzaville'] }] },
  { name: 'Congo (DRC)', code: '+243', states: [{ name: 'Kinshasa', cities: ['Kinshasa'] }] },
  { name: 'Costa Rica', code: '+506', states: [{ name: 'San José', cities: ['San José'] }] },
  { name: 'Croatia', code: '+385', states: [{ name: 'Zagreb', cities: ['Zagreb'] }] },
  { name: 'Cuba', code: '+53', states: [{ name: 'La Habana', cities: ['Havana'] }] },
  { name: 'Cyprus', code: '+357', states: [{ name: 'Nicosia', cities: ['Nicosia'] }] },
  { name: 'Czechia', code: '+420', states: [{ name: 'Prague', cities: ['Prague'] }] },
  { name: 'Denmark', code: '+45', states: [{ name: 'Capital', cities: ['Copenhagen'] }] },
  { name: 'Djibouti', code: '+253', states: [{ name: 'Djibouti', cities: ['Djibouti'] }] },
  { name: 'Dominica', code: '+1-767', states: [{ name: 'Saint George', cities: ['Roseau'] }] },
  { name: 'Dominican Republic', code: '+1-809', states: [{ name: 'Distrito Nacional', cities: ['Santo Domingo'] }] },
  { name: 'Ecuador', code: '+593', states: [{ name: 'Pichincha', cities: ['Quito'] }] },
  { name: 'Egypt', code: '+20', states: [{ name: 'Cairo', cities: ['Cairo'] }] },
  { name: 'El Salvador', code: '+503', states: [{ name: 'San Salvador', cities: ['San Salvador'] }] },
  { name: 'Equatorial Guinea', code: '+240', states: [{ name: 'Bioko Norte', cities: ['Malabo'] }] },
  { name: 'Eritrea', code: '+291', states: [{ name: 'Maekel', cities: ['Asmara'] }] },
  { name: 'Estonia', code: '+372', states: [{ name: 'Harju', cities: ['Tallinn'] }] },
  { name: 'Eswatini', code: '+268', states: [{ name: 'Hhohho', cities: ['Mbabane'] }] },
  { name: 'Ethiopia', code: '+251', states: [{ name: 'Addis Ababa', cities: ['Addis Ababa'] }] },
  { name: 'Fiji', code: '+679', states: [{ name: 'Central', cities: ['Suva'] }] },
  { name: 'Finland', code: '+358', states: [{ name: 'Uusimaa', cities: ['Helsinki'] }] },
  { name: 'France', code: '+33', states: [{ name: 'Île-de-France', cities: ['Paris'] }] },
  { name: 'Gabon', code: '+241', states: [{ name: 'Estuaire', cities: ['Libreville'] }] },
  { name: 'Gambia', code: '+220', states: [{ name: 'Banjul', cities: ['Banjul'] }] },
  { name: 'Georgia', code: '+995', states: [{ name: 'Tbilisi', cities: ['Tbilisi'] }] },
  { name: 'Germany', code: '+49', states: [{ name: 'Berlin', cities: ['Berlin'] }] },
  { name: 'Ghana', code: '+233', states: [{ name: 'Greater Accra', cities: ['Accra'] }] },
  { name: 'Greece', code: '+30', states: [{ name: 'Attica', cities: ['Athens'] }] },
  { name: 'Grenada', code: '+1-473', states: [{ name: 'Saint George', cities: ['St. George’s'] }] },
  { name: 'Guatemala', code: '+502', states: [{ name: 'Guatemala', cities: ['Guatemala City'] }] },
  { name: 'Guinea', code: '+224', states: [{ name: 'Conakry', cities: ['Conakry'] }] },
  { name: 'Guinea-Bissau', code: '+245', states: [{ name: 'Bissau', cities: ['Bissau'] }] },
  { name: 'Guyana', code: '+592', states: [{ name: 'Demerara-Mahaica', cities: ['Georgetown'] }] },
  { name: 'Haiti', code: '+509', states: [{ name: 'Ouest', cities: ['Port-au-Prince'] }] },
  { name: 'Honduras', code: '+504', states: [{ name: 'Francisco Morazán', cities: ['Tegucigalpa'] }] },
  { name: 'Hungary', code: '+36', states: [{ name: 'Central Hungary', cities: ['Budapest'] }] },
  { name: 'Iceland', code: '+354', states: [{ name: 'Capital', cities: ['Reykjavík'] }] },
  { name: 'India', code: '+91', states: [{ name: 'Maharashtra', cities: ['Mumbai'] }] },
  { name: 'Indonesia', code: '+62', states: [{ name: 'Jakarta', cities: ['Jakarta'] }] },
  { name: 'Iran', code: '+98', states: [{ name: 'Tehran', cities: ['Tehran'] }] },
  { name: 'Iraq', code: '+964', states: [{ name: 'Baghdad', cities: ['Baghdad'] }] },
  { name: 'Ireland', code: '+353', states: [{ name: 'Leinster', cities: ['Dublin'] }] },
  { name: 'Israel', code: '+972', states: [{ name: 'Jerusalem', cities: ['Jerusalem'] }] },
  { name: 'Italy', code: '+39', states: [{ name: 'Lazio', cities: ['Rome'] }] },
  { name: 'Jamaica', code: '+1-876', states: [{ name: 'Kingston', cities: ['Kingston'] }] },
  { name: 'Japan', code: '+81', states: [{ name: 'Tokyo', cities: ['Tokyo'] }] },
  { name: 'Jordan', code: '+962', states: [{ name: 'Amman', cities: ['Amman'] }] },
  { name: 'Kazakhstan', code: '+7', states: [{ name: 'Almaty', cities: ['Almaty'] }] },
  { name: 'Kenya', code: '+254', states: [{ name: 'Nairobi', cities: ['Nairobi'] }] },
  { name: 'Kiribati', code: '+686', states: [{ name: 'Gilbert Islands', cities: ['Tarawa'] }] },
  { name: 'Kuwait', code: '+965', states: [{ name: 'Al Asimah', cities: ['Kuwait City'] }] },
  { name: 'Kyrgyzstan', code: '+996', states: [{ name: 'Bishkek', cities: ['Bishkek'] }] },
  { name: 'Laos', code: '+856', states: [{ name: 'Vientiane', cities: ['Vientiane'] }] },
  { name: 'Latvia', code: '+371', states: [{ name: 'Riga', cities: ['Riga'] }] },
  { name: 'Lebanon', code: '+961', states: [{ name: 'Beirut', cities: ['Beirut'] }] },
  { name: 'Lesotho', code: '+266', states: [{ name: 'Maseru', cities: ['Maseru'] }] },
  { name: 'Liberia', code: '+231', states: [{ name: 'Montserrado', cities: ['Monrovia'] }] },
  { name: 'Libya', code: '+218', states: [{ name: 'Tripoli', cities: ['Tripoli'] }] },
  { name: 'Liechtenstein', code: '+423', states: [{ name: 'Vaduz', cities: ['Vaduz'] }] },
  { name: 'Lithuania', code: '+370', states: [{ name: 'Vilnius', cities: ['Vilnius'] }] },
  { name: 'Luxembourg', code: '+352', states: [{ name: 'Luxembourg', cities: ['Luxembourg'] }] },
  { name: 'Madagascar', code: '+261', states: [{ name: 'Analamanga', cities: ['Antananarivo'] }] },
  { name: 'Malawi', code: '+265', states: [{ name: 'Lilongwe', cities: ['Lilongwe'] }] },
  { name: 'Malaysia', code: '+60', states: [{ name: 'Kuala Lumpur', cities: ['Kuala Lumpur'] }] },
  { name: 'Maldives', code: '+960', states: [{ name: 'Malé', cities: ['Malé'] }] },
  { name: 'Mali', code: '+223', states: [{ name: 'Bamako', cities: ['Bamako'] }] },
  { name: 'Malta', code: '+356', states: [{ name: 'Malta', cities: ['Valletta'] }] },
  { name: 'Marshall Islands', code: '+692', states: [{ name: 'Majuro', cities: ['Majuro'] }] },
  { name: 'Mauritania', code: '+222', states: [{ name: 'Nouakchott', cities: ['Nouakchott'] }] },
  { name: 'Mauritius', code: '+230', states: [{ name: 'Port Louis', cities: ['Port Louis'] }] },
  { name: 'Mexico', code: '+52', states: [{ name: 'Mexico City', cities: ['Mexico City'] }] },
  { name: 'Micronesia', code: '+691', states: [{ name: 'Pohnpei', cities: ['Palikir'] }] },
  { name: 'Moldova', code: '+373', states: [{ name: 'Chișinău', cities: ['Chișinău'] }] },
  { name: 'Monaco', code: '+377', states: [{ name: 'Monaco', cities: ['Monaco'] }] },
  { name: 'Mongolia', code: '+976', states: [{ name: 'Ulaanbaatar', cities: ['Ulaanbaatar'] }] },
  { name: 'Montenegro', code: '+382', states: [{ name: 'Podgorica', cities: ['Podgorica'] }] },
  { name: 'Morocco', code: '+212', states: [{ name: 'Rabat-Salé-Kénitra', cities: ['Rabat'] }] },
  { name: 'Mozambique', code: '+258', states: [{ name: 'Maputo', cities: ['Maputo'] }] },
  { name: 'Myanmar', code: '+95', states: [{ name: 'Yangon', cities: ['Yangon'] }] },
  { name: 'Namibia', code: '+264', states: [{ name: 'Khomas', cities: ['Windhoek'] }] },
  { name: 'Nauru', code: '+674', states: [{ name: 'Yaren', cities: ['Yaren'] }] },
  { name: 'Nepal', code: '+977', states: [{ name: 'Bagmati', cities: ['Kathmandu'] }] },
  { name: 'Netherlands', code: '+31', states: [{ name: 'North Holland', cities: ['Amsterdam'] }] },
  { name: 'New Zealand', code: '+64', states: [{ name: 'Auckland', cities: ['Auckland'] }] },
  { name: 'Nicaragua', code: '+505', states: [{ name: 'Managua', cities: ['Managua'] }] },
  { name: 'Niger', code: '+227', states: [{ name: 'Niamey', cities: ['Niamey'] }] },
  { name: 'Nigeria', code: '+234', states: [{ name: 'Lagos', cities: ['Ikeja'] }, { name: 'Rivers', cities: ['Port Harcourt'] }] },
  { name: 'North Korea', code: '+850', states: [{ name: 'Pyongyang', cities: ['Pyongyang'] }] },
  { name: 'North Macedonia', code: '+389', states: [{ name: 'Skopje', cities: ['Skopje'] }] },
  { name: 'Norway', code: '+47', states: [{ name: 'Oslo', cities: ['Oslo'] }] },
  { name: 'Oman', code: '+968', states: [{ name: 'Muscat', cities: ['Muscat'] }] },
  { name: 'Pakistan', code: '+92', states: [{ name: 'Punjab', cities: ['Lahore'] }] },
  { name: 'Palau', code: '+680', states: [{ name: 'Koror', cities: ['Koror'] }] },
  { name: 'Palestine', code: '+970', states: [{ name: 'West Bank', cities: ['Ramallah'] }] },
  { name: 'Panama', code: '+507', states: [{ name: 'Panamá', cities: ['Panama City'] }] },
  { name: 'Papua New Guinea', code: '+675', states: [{ name: 'National Capital', cities: ['Port Moresby'] }] },
  { name: 'Paraguay', code: '+595', states: [{ name: 'Asunción', cities: ['Asunción'] }] },
  { name: 'Peru', code: '+51', states: [{ name: 'Lima', cities: ['Lima'] }] },
  { name: 'Philippines', code: '+63', states: [{ name: 'Metro Manila', cities: ['Manila'] }] },
  { name: 'Poland', code: '+48', states: [{ name: 'Masovian', cities: ['Warsaw'] }] },
  { name: 'Portugal', code: '+351', states: [{ name: 'Lisbon', cities: ['Lisbon'] }] },
  { name: 'Qatar', code: '+974', states: [{ name: 'Doha', cities: ['Doha'] }] },
  { name: 'Romania', code: '+40', states: [{ name: 'Bucharest', cities: ['Bucharest'] }] },
  { name: 'Russia', code: '+7', states: [{ name: 'Moscow', cities: ['Moscow'] }] },
  { name: 'Rwanda', code: '+250', states: [{ name: 'Kigali', cities: ['Kigali'] }] },
  { name: 'Saint Kitts and Nevis', code: '+1-869', states: [{ name: 'Saint George Basseterre', cities: ['Basseterre'] }] },
  { name: 'Saint Lucia', code: '+1-758', states: [{ name: 'Castries', cities: ['Castries'] }] },
  { name: 'Saint Vincent and the Grenadines', code: '+1-784', states: [{ name: 'Saint George', cities: ['Kingstown'] }] },
  { name: 'Samoa', code: '+685', states: [{ name: 'Tuamasaga', cities: ['Apia'] }] },
  { name: 'San Marino', code: '+378', states: [{ name: 'San Marino', cities: ['San Marino'] }] },
  { name: 'Sao Tome and Principe', code: '+239', states: [{ name: 'Água Grande', cities: ['São Tomé'] }] },
  { name: 'Saudi Arabia', code: '+966', states: [{ name: 'Riyadh', cities: ['Riyadh'] }] },
  { name: 'Senegal', code: '+221', states: [{ name: 'Dakar', cities: ['Dakar'] }] },
  { name: 'Serbia', code: '+381', states: [{ name: 'Belgrade', cities: ['Belgrade'] }] },
  { name: 'Seychelles', code: '+248', states: [{ name: 'Mahé', cities: ['Victoria'] }] },
  { name: 'Sierra Leone', code: '+232', states: [{ name: 'Western Area', cities: ['Freetown'] }] },
  { name: 'Singapore', code: '+65', states: [{ name: 'Central', cities: ['Singapore'] }] },
  { name: 'Slovakia', code: '+421', states: [{ name: 'Bratislava', cities: ['Bratislava'] }] },
  { name: 'Slovenia', code: '+386', states: [{ name: 'Ljubljana', cities: ['Ljubljana'] }] },
  { name: 'Solomon Islands', code: '+677', states: [{ name: 'Guadalcanal', cities: ['Honiara'] }] },
  { name: 'Somalia', code: '+252', states: [{ name: 'Banaadir', cities: ['Mogadishu'] }] },
  { name: 'South Africa', code: '+27', states: [{ name: 'Gauteng', cities: ['Johannesburg'] }] },
  { name: 'South Korea', code: '+82', states: [{ name: 'Seoul', cities: ['Seoul'] }] },
  { name: 'South Sudan', code: '+211', states: [{ name: 'Central Equatoria', cities: ['Juba'] }] },
  { name: 'Spain', code: '+34', states: [{ name: 'Madrid', cities: ['Madrid'] }] },
  { name: 'Sri Lanka', code: '+94', states: [{ name: 'Western', cities: ['Colombo'] }] },
  { name: 'Sudan', code: '+249', states: [{ name: 'Khartoum', cities: ['Khartoum'] }] },
  { name: 'Suriname', code: '+597', states: [{ name: 'Paramaribo', cities: ['Paramaribo'] }] },
  { name: 'Sweden', code: '+46', states: [{ name: 'Stockholm', cities: ['Stockholm'] }] },
  { name: 'Switzerland', code: '+41', states: [{ name: 'Zurich', cities: ['Zurich'] }] },
  { name: 'Syria', code: '+963', states: [{ name: 'Damascus', cities: ['Damascus'] }] },
  { name: 'Taiwan', code: '+886', states: [{ name: 'Taipei', cities: ['Taipei'] }] },
  { name: 'Tajikistan', code: '+992', states: [{ name: 'Dushanbe', cities: ['Dushanbe'] }] },
  { name: 'Tanzania', code: '+255', states: [{ name: 'Dar es Salaam', cities: ['Dar es Salaam'] }] },
  { name: 'Thailand', code: '+66', states: [{ name: 'Bangkok', cities: ['Bangkok'] }] },
  { name: 'Timor-Leste', code: '+670', states: [{ name: 'Dili', cities: ['Dili'] }] },
  { name: 'Togo', code: '+228', states: [{ name: 'Maritime', cities: ['Lomé'] }] },
  { name: 'Tonga', code: '+676', states: [{ name: 'Tongatapu', cities: ['Nukuʻalofa'] }] },
  { name: 'Trinidad and Tobago', code: '+1-868', states: [{ name: 'Port of Spain', cities: ['Port of Spain'] }] },
  { name: 'Tunisia', code: '+216', states: [{ name: 'Tunis', cities: ['Tunis'] }] },
  { name: 'Turkey', code: '+90', states: [{ name: 'Istanbul', cities: ['Istanbul'] }] },
  { name: 'Turkmenistan', code: '+993', states: [{ name: 'Ahal', cities: ['Ashgabat'] }] },
  { name: 'Tuvalu', code: '+688', states: [{ name: 'Funafuti', cities: ['Funafuti'] }] },
  { name: 'Uganda', code: '+256', states: [{ name: 'Central', cities: ['Kampala'] }] },
  { name: 'Ukraine', code: '+380', states: [{ name: 'Kyiv', cities: ['Kyiv'] }] },
  { name: 'United Arab Emirates', code: '+971', states: [{ name: 'Dubai', cities: ['Dubai'] }] },
  { name: 'United Kingdom', code: '+44', states: [{ name: 'England', cities: ['London'] }] },
  { name: 'United States', code: '+1', states: [{ name: 'California', cities: ['Los Angeles'] }] },
  { name: 'Uruguay', code: '+598', states: [{ name: 'Montevideo', cities: ['Montevideo'] }] },
  { name: 'Uzbekistan', code: '+998', states: [{ name: 'Tashkent', cities: ['Tashkent'] }] },
  { name: 'Vanuatu', code: '+678', states: [{ name: 'Shefa', cities: ['Port Vila'] }] },
  { name: 'Vatican City', code: '+379', states: [{ name: 'Vatican City', cities: ['Vatican City'] }] },
  { name: 'Venezuela', code: '+58', states: [{ name: 'Distrito Capital', cities: ['Caracas'] }] },
  { name: 'Vietnam', code: '+84', states: [{ name: 'Hanoi', cities: ['Hanoi'] }] },
  { name: 'Yemen', code: '+967', states: [{ name: 'Sana’a', cities: ['Sana’a'] }] },
  { name: 'Zambia', code: '+260', states: [{ name: 'Lusaka', cities: ['Lusaka'] }] },
  { name: 'Zimbabwe', code: '+263', states: [{ name: 'Harare', cities: ['Harare'] }] }
];

export default countryData;
